name: Proofreading
author: David Guest
markdown: redcarpet
pygments: true
baseurl: http://proofreading.website
description: theme for jekyll
github: http://www.github.com/proofreading-website
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: davidguest[at]proofreading.website
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

